update

diff --git a/mole b/mole
--- a/mole
+++ b/mole
@@ -6,7 +6,7 @@ export LC_NUMERIC=en_US.UTF-8
 # FUNCTIONS
 
 openEditor () { #Open file using EDITOR, VISUAL or vi.
-	#if [ -f "$1" ]; then
+	if [ -f "$1" ]; then
 		fileDir=$(dirname "$1")
 		if ! [ -d "fileDir" ]; then
 				fileDir=$PWD
@@ -28,10 +28,10 @@ openEditor () { #Open file using EDITOR, VISUAL or vi.
 		fi
 
 		exit
-	#else
-	#	echo "$1 is not a file. Cant open editor" >&2
-	#	exit 1
-	#fi		
+	else
+		echo "$1 is not a file. Cant open editor" >&2
+		exit 1
+	fi		
 }
 
 help()
@@ -62,7 +62,7 @@ FILTERS:
 
 # MOLE_RC condition check
 if [ -z "$MOLE_RC" ]; then
-	echo "MOLE_RC neexistuje" >&2
+	echo "ERROR: MOLE_RC neexistuje" >&2
 	exit 1
 elif ! [ -f "$MOLE_RC" ]; then
 	mkdir -p "$(dirname "$MOLE_RC")" && touch "$MOLE_RC"
@@ -74,9 +74,8 @@ directory="$PWD"	# [DIRECTORY]
 
 groupFilter=""		# -g
 mostFrequent=false	# -m
-dateBefore=""		# -a
-dateAfter=""		# -b
-dateIgnored=""		# -d
+dateAfter=""		# -a
+dateIgnored=""		# -b
 listSecond=false	# list
 secretLog=false		# secret-log
 
@@ -97,7 +96,7 @@ if [ -d "$lastArg" ] && [ "$#" != "0" ]; then
 	directory=$lastArg
 fi
 
-while getopts "hmg:a:b:d:" opt; do
+while getopts "hmg:a:b:" opt; do
     case $opt in
 	h)
 	   help
@@ -111,25 +110,10 @@ while getopts "hmg:a:b:d:" opt; do
 		groupFilter="$OPTARG"
     	;;
 	a)
-		dateBefore="$OPTARG"
-		if ! [[ $input_date =~ ^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$ ]]; then
-			echo "Data format is incorrect. Please use YYYY-MM-DD data format." >&2
-			exit 1
-		fi
-		;;
-	b)
 		dateAfter="$OPTARG"
-		if ! [[ $input_date =~ ^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$ ]]; then
-			echo "Data format is incorrect. Please use YYYY-MM-DD data format." >&2
-			exit 1
-		fi
 		;;
-    d)
+    b)
 		dateIgnored="$OPTARG"
-		if ! [[ $input_date =~ ^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$ ]]; then
-			echo "Data format is incorrect. Please use YYYY-MM-DD data format." >&2
-			exit 1
-		fi
     	;;
     \?)
         echo "Wrong flag: -$OPTARG" >&2
@@ -145,8 +129,9 @@ done
 shift $((OPTIND-1))
 
 # Realization of calling "mole [-g GROUP] FILE"
-if [ "$#" = "1" ] && ! [ -d "$1" ] && [ "$mostFrequent" = false ] && [ "$listSecond" = false ] && [ "$secretLog" = false ] && [ -z "$dateBefore" ] && [ -z "$dateAfter" ] && [ -z "$dateIgnored" ]; then 	
-	openEditor "$1" 
+if [ -f "$1" ] && [ "$#" = "1" ]; then # check if lastArg is a file.	
+	 		openEditor "$1" 
+
 else
 		fResult=$(grep -r "$directory" "$MOLE_RC")
 		# Check if user used another avalible arguments
@@ -166,17 +151,12 @@ else
 
 		# Date ignored
 		if [ -n "$dateIgnored" ] && ! [ -d "$dateIgnored" ] && ! [ -f "$dateAfter" ]; then
-			fResult=$(echo "$fResult" | awk -v ignored="$dateIgnored" '{ if ($0 !~ ignored) print }')
+			fResult=$(echo "$fResult" | awk -v d="$dateIgnored" -F',' '{if ($4 >= d) print $0}')
 		fi 
 
 		# Date after
 		if [ -n "$dateAfter" ] && ! [ -d "$dateAfter" ] && ! [ -f "$dateAfter" ]; then
-			fResult=$(echo "$fResult" | awk -v d="$dateAfter" -F',' '{if ($4 >= d) print $0}')
-		fi
-
-		# Date before
-		if [ -n "$dateBefore" ] && ! [ -d "$dateBefore" ] && ! [ -f "$dateBefore" ]; then
-			fResult=$(echo "$fResult" | awk -v d="$dateBefore" -F',' '{if (d > $4) print $0}')
+			fResult=$(echo "$fResult" | awk -v d="$dateAfter" -F',' '{if ($4 <= d) print $0}')
 		fi
 
 		# Realization of calling "mole list [FILTERS] [DIRECTORY]"
@@ -222,16 +202,11 @@ else
 			done
 			# Date ignored
 			if [ -n "$dateIgnored" ]; then
-				secretLogResult=$(echo "$secretLogResult" | awk -v ignrd="$dateIgnored" '{ if ($0 !~ ignrd) print }')
+				secretLogResult=$(echo "$secretLogResult" | awk -v a="$dateIgnored" -F',' '{if ($4 >= a) print $0}')
 			fi
 			# Date after
 			if [ -n "$dateAfter" ]; then
-				secretLogResult=$(echo "$secretLogResult" | awk -v a="$dateAfter" -F',' '{if ($4 >= a) print $0}')
-			fi
-
-			# Date before
-			if [ -n "$dateBefore" ]; then
-				secretLogResult=$(echo "$secretLogResult" | awk -v a="$dateBefore" -F',' '{if (a > $4) print $0}')
+				secretLogResult=$(echo "$secretLogResult" | awk -v a="$dateAfter" -F',' '{if ($4 <= a) print $0}')
 			fi
 			
 			secretLogResult=$(echo "$secretLogResult" | awk 'NF' | awk -F',' '{print $3 ";" $4}' | sort)
@@ -257,8 +232,7 @@ else
 		else
 
 		# Realization of calling "mole [-m] [FILTERS] [DIRECTORY]"
-		fResult=$(echo "$fResult" | awk -F',' '{a[i++]=$2} END {for (j=i-1; j>=0;) print a[j--] }')
-
+		fResult=$(echo "$fResult" | awk -F',' '{a[i++]=$2} END {for (j=i-1; j>=0;) print a[j--] }') 
 
 		# the most frequent file
 		if [ "$mostFrequent" = "true" ]; then
